# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ICON_Swift_Part2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ICONKit', '~> 0.4.3'

end
